name: Publish Docker Image

on:
  push:
    tags:
      - '*.*.*'
      - '!*.*.*-*'
env:
  PLATFORMS: "linux/amd64,linux/arm/v7,linux/arm64/v8"

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      # https://stackoverflow.com/questions/58177786
      - name: Get version
        run: echo "GIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: ${{ env.PLATFORMS }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.GIT_TAG }}
            ghcr.io/${{ github.repository }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
